name: build-docs-workflow
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - next
    workflow_dispatch:
jobs:
    build-docs:
        name: "Build Sphinx docs"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Pilot 3 repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                architecture: x64

            - name: Pip install
              run: pip install sphinx furo

            - name: Check sphinx version
              run: python -c "import sphinx;print(sphinx.__version__)"

            - name: Build docs locally to catch errors
              run: cd doc && make html

            - name: Trigger panda-docs webhook
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              env:
                READDOCS_TOKEN: ${{ secrets.READDOCS_TOKEN }}
                READDOCS_HOOK: ${{ secrets.READDOCS_HOOK }}
              run: curl -X POST -d "token=$READDOCS_TOKEN" $READDOCS_HOOK
