name: unit-tests-workflow
on:
    pull_request:
        branches:
            - master
            - next
jobs:
    run-unit-tests:
        name: "Run unit tests"
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
            matrix:
                python-version: ["3.9", "3.11", "3.12"]
        steps:
            - name: Checkout Pilot3 repo
              uses: actions/checkout@v3

            - name: Setup Python3
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
                architecture: x64

            - name: Run unit tests
              run: python -m unittest
